#------------------------------------------------------------------------------
#
#  $Id$
#
#  Copyright (C) 2006-2008  Florian Pose, Ingenieurgemeinschaft IgH
#
#  This file is part of the IgH EtherCAT Master.
#
#  The IgH EtherCAT Master is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License version 2, as
#  published by the Free Software Foundation.
#
#  The IgH EtherCAT Master is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with the IgH EtherCAT Master; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#  ---
#
#  The license mentioned above concerns the source code only. Using the
#  EtherCAT technology and brand is only permitted in compliance with the
#  industrial property and similar rights of Beckhoff Automation GmbH.
#
#  ---
#
#  vi: syntax=make
#
#------------------------------------------------------------------------------

obj-m := ec_dc_rtai_sample.o

ec_dc_rtai_sample-objs := dc_rtai_sample.o

EXTRA_CFLAGS := -I/include

KBUILD_EXTRA_SYMBOLS := \
	/media/root/48e0f43c-e356-4ad3-b6e8-1981623c64a5/workspace/ethercat-master/$(LINUX_SYMVERS) \
	/media/root/48e0f43c-e356-4ad3-b6e8-1981623c64a5/workspace/ethercat-master/master/$(LINUX_SYMVERS)

#------------------------------------------------------------------------------
